---
title: "Dissertation Analytics Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

```{r Load Packages, include=FALSE}
library(gdata) #Open gdata: this package allows you to open .xls files.
library(lavaan) #For running factor analyses: Download and open the 'lavaan' package. 
library(faoutlier) #Checking for multivariate outliers using "faoutlier
library(car)
library(psych)
library(ggplot2)
library(graphics)
library(tidyverse)
library(semTools)
library(semPlot)
library(MVN) #Testing for Multivariate Normality
set.seed(1234)
```

The code below simply loads the data into r. The "gdata" package simply allows '.csv' files to be read. 
```{r Load Data, include = TRUE}
Diss_Final_Datafile_CLEANED <- read.csv("data.csv")

#Subset data into a new dataframe called "likert". This dataframe contains only likert scaled data (i.e., your item response data).
likert <- Diss_Final_Datafile_CLEANED[c(4,5,7:10,12:31,34:38,40:43,47,48)]

#Classify likert-type data as numeric. 
likert <- as.data.frame(lapply(likert, as.numeric))
```

Below, I checked for multivariate normality.
```{r Checking Assumptions, include = TRUE}
#result <- mardiaTest(likert, cov = FALSE, qqplot = TRUE)
result <- mvn(likert, mvnTest = "mardia", covariance = FALSE)
result
result1 <- mvn(likert, mvnTest = "hz")
result1

#Excluding outliers. Note: these outliers were identififed using generalized Cook's distance. See subsequent "Model Testing" section.
dm7 <- likert[-c(535, 433, 756, 73, 28, 482, 681), ]
```

```{r Include Conditions and Interactions, include = TRUE}
#Create conditional/moderator dataset and bind to likert dataset.
cond <- Diss_Final_Datafile_CLEANED[c(6,62,64,67)]

#Remove outliers
cond <- cond[-c(535, 433, 756, 73, 28, 482, 681), ]
#Positive Valence is 1
#Negative Valence is 2

#Define the 'cond' dataframe as numeric.
cond <- as.data.frame(lapply(cond, as.numeric))
#"Paratelic" =  1
#"Telic" = 2

#Recode Moderator variables.
cond$FdbkTypeN<-car::recode(cond$FdbkTypeN,"1=2;2=1")
#Nominal Feedback is 2
#Relative Feedback is 1
cond$FdbkValN<-car::recode(cond$FdbkValN,"1=2;2=1")
#Positive Valence is NOW 2.
#Negative Valence is NOW 1.
cond$FdbkAccN<-car::recode(cond$FdbkAccN,"1=2;2=1")
#Accurate Feedback is 2
#Inaccurate Feedback is 1

#get condition counts
#1=negative,2=positive;1=inaccurate,2=accurate;1=relative,2=nominal
cond %>% 
  group_by(FdbkTypeN,FdbkValN,FdbkAccN) %>%
  tally()

#Bind cond to likert/dm7
data <- cbind(cond,dm7)

#Create the interaction terms (mean centered).
##Feedback Accuracy and Information Type.
data$INTAccType <- (data$FdbkAccN-(mean(data$FdbkAccN))) * (data$FdbkTypeN-(mean(data$FdbkTypeN)))
##Paratelic and Feedback Accuracy.
data$INTParaFkAcc <- (data$ParTelic-(mean(data$ParTelic))) * (data$FdbkAccN-(mean(data$FdbkAccN)))
##Paratelic and Feedback Valence.
data$INTParaFkVal <- (data$ParTelic-(mean(data$ParTelic))) * (data$FdbkValN-(mean(data$FdbkValN)))

##Extract goal revision and performance change data. Add in task difficulty variables.
grpc <- Diss_Final_Datafile_CLEANED[c(69,70,74,75)]
grpc <- grpc[-c(535, 433, 756, 73, 28, 482, 681), ]

#Bind goal revision and performance change to main dataset.
data <- cbind(data,grpc)
```

```{r Model Testing Respecification and Visualization, include = TRUE}
#CFA1 
DissCFA1 <- ' 
# Latent Variables
              DJ =~ DisJust1 + DisJust2  + DisJust3 + DisJust4
              POFA =~ PercepAcc1 + PercepAcc2 + PercepAcc3 + PercepAcc4Reco + PercepAcc5
              PA =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert
              Na =~ Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable
'
fit1 <- lavaan::cfa(DissCFA1, likert,std.lv = TRUE,  estimator = "WLSMV")
MI <- modindices(fit1)
summary(fit1, fit.measures=TRUE, standardized = TRUE)
htmt(DissCFA1,likert)
write.csv(MI, file = "DissCFA1MI.csv")

#CFA2 POFA and DJ combined
DissCFA1b <- ' 
# Latent Variables
              DJPOFA =~ DisJust1 + DisJust2  + DisJust3 + DisJust4 + PercepAcc1 + PercepAcc2 + PercepAcc3 + PercepAcc4Reco + PercepAcc5
              PA =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert
              Na =~ Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable
'
fit1b <- lavaan::cfa(DissCFA1b, data, std.lv = TRUE, estimator = "WLSMV")
MI <- modindices(fit1b)
summary(fit1b, fit.measures=TRUE, standardized = TRUE)
htmt(DissCFA1b,data)
write.csv(MI, file = "DissCFA1MI.csv")

# Compare the two models to determine if POFA and DJ should be modeled jointly.
anova(fit1, fit1b)

DissCFA2 <- ' #Bifactor added
  # latent variable definitions - Bifactor added
    POFA   =~ PercepAcc1 + PercepAcc2 + PercepAcc3 + PercepAcc4Reco + PercepAcc5
    PA =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert
    Na =~ Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable
    DJ =~ DisJust1 + DisJust2  + DisJust3 + DisJust4

#Bifactor
AffPolarity =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert + Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable

#Constrain PA and Na covariances with affective polarity to be 0.
    PA~~0*Na
    PA~~0*AffPolarity
    Na~~0*AffPolarity
'
fit2 <- lavaan::cfa(DissCFA2, data, std.lv = TRUE, estimator = "WLSMV")
MI <- modindices(fit2)
summary(fit2, fit.measures=TRUE, standardized = TRUE)
write.csv(MI, file = "DissCFA1M3.csv")
anova(fit1,fit2) 

#Print Cronbach alphas
reliability(fit2)

#SEM 
DissSEM1 <- ' #includes the condition and goal 
  # latent variable definitions - Bifactor added
    POFA   =~ PercepAcc1 + PercepAcc2 + PercepAcc3 + PercepAcc4Reco + PercepAcc5
    PA =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert
    Na =~ Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable
    DJ =~ DisJust1 + DisJust2  + DisJust3 + DisJust4

#Bifactor
    AffPolarity =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert + Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable

#Constrain PA and Na covariance to 0
    PA~~0*Na
    PA~~0*AffPolarity
    Na~~0*AffPolarity

#Outcome Model
  Perf1 ~ Goal1Lvl
  Perf2 ~ f11*Goal2Lvl + Perf1
  
#Mediators Model
  Goal2Lvl ~ Goal1Lvl + e1*PA + e2*Na + e3*DJ + a41*FdbkValN
  DJ ~ c21*POFA
  POFA ~ a31*FdbkValN + b42*INTAccType
  PA ~ a11*FdbkValN + d21*DJ
  Na ~ a21*FdbkValN + d11*DJ
'

#Fit SEM to data
fit <- lavaan::sem(DissSEM1, data, std.lv = TRUE, estimator = "WLSMV")
summary(fit, fit.measures=TRUE, standardized = TRUE, rsquare=TRUE, ci=TRUE)
MI <- modindices(fit)
write.csv(MI, file = "DissSEM.csv")
factor.scores <- predict(fit)
factor.scores <- as.data.frame(factor.scores)
factor.scores <- as.data.frame(factor.scores$POFA)
names(factor.scores) <- c("POFA")

# Add in the feedback valence -> DJ effect
DissSEM2 <- '#includes the condition and goal 
  # latent variable definitions - Bifactor added
    POFA   =~ PercepAcc1 + PercepAcc2 + PercepAcc3 + PercepAcc4Reco + PercepAcc5
    PA =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert
    Na =~ Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable
    DJ =~ DisJust1 + DisJust2  + DisJust3 + DisJust4

#Bifactor
    AffPolarity =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert + Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable

#Constrain PA and Na covariance to 0
    PA~~0*Na
    PA~~0*AffPolarity
    Na~~0*AffPolarity

#Outcome Model
  Perf1 ~ Goal1Lvl
  Perf2 ~ f11*Goal2Lvl + Perf1
  
#Mediators Model
  Goal2Lvl ~ Goal1Lvl + e1*PA + e2*Na + e3*DJ + a41*FdbkValN
  DJ ~ c21*POFA
  POFA ~ a31*FdbkValN + b42*INTAccType
  PA ~ a11*FdbkValN + d21*DJ
  Na ~ a21*FdbkValN + d11*DJ
'
#Fit SEM to data
fitb <- lavaan::sem(DissSEM2, data, std.lv = TRUE, estimator = "WLSMV")
summary(fitb, fit.measures=TRUE, standardized = TRUE, rsquare=TRUE, ci=TRUE)
MI <- modindices(fitb)
write.csv(MI, file = "DissSEM.csv")
factor.scores <- predict(fitb)
factor.scores <- as.data.frame(factor.scores)
factor.scores <- as.data.frame(factor.scores$POFA)
names(factor.scores) <- c("POFA")

#compare models
anova(fit,fitb)

# Fix the [PA,NA] -> GS effects to zero since they are non-significant, add in the feedback accuracy and feedback information type conditions.
DissSEM3 <- '
  # latent variable definitions - Bifactor added
    POFA   =~ PercepAcc1 + PercepAcc2 + PercepAcc3 + PercepAcc4Reco + PercepAcc5
    PA =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert
    Na =~ Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable
    DJ =~ DisJust1 + DisJust2  + DisJust3 + DisJust4

#Bifactor
Activation =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert + Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable

#Constrain PA and Na covariance to 0
    PA~~0*Na
    PA~~0*Activation
    Na~~0*Activation

#Outcome Model
  Perf1 ~ Goal1Lvl
  Perf2 ~ f11*Goal2Lvl + Perf1
  
#Mediators Model
  Goal2Lvl ~ Goal1Lvl + e3*DJ + a41*FdbkValN + 0*PA + 0*Na
  DJ ~ c21*POFA + FdbkValN
  POFA ~ a31*FdbkValN + b42*INTAccType + FdbkAccN + FdbkTypeN
  PA ~ a11*FdbkValN + d21*DJ
  Na ~ a21*FdbkValN + d11*DJ
'
#Fit SEM to data
fitc <- lavaan::sem(DissSEM3, data, std.lv = TRUE, estimator = "WLSMV")
summary(fitc, fit.measures=TRUE, standardized = TRUE, rsquare=TRUE, ci=TRUE)
MI <- modindices(fitc)
write.csv(MI, file = "DissSEM.csv")
factor.scores <- predict(fitb)
factor.scores <- as.data.frame(factor.scores)
factor.scores <- as.data.frame(factor.scores$POFA)
names(factor.scores) <- c("POFA")

# Add in the DJ -> affective polarity link
DissSEM4 <- '
  # latent variable definitions - Bifactor added
    POFA   =~ PercepAcc1 + PercepAcc2 + PercepAcc3 + PercepAcc4Reco + PercepAcc5
    PA =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert
    Na =~ Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable
    DJ =~ DisJust1 + DisJust2  + DisJust3 + DisJust4

#Bifactor
Activation =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert + Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable

#Constrain PA and Na covariance to 0
    PA~~0*Na
    PA~~0*Activation
    Na~~0*Activation

#Outcome Model
  Perf1 ~ Goal1Lvl
  Perf2 ~ f11*Goal2Lvl + Perf1
  
#Mediators Model
  Goal2Lvl ~ Goal1Lvl + e3*DJ + a41*FdbkValN + 0*PA + 0*Na
  DJ ~ c21*POFA + FdbkValN
  POFA ~ a31*FdbkValN + b42*INTAccType + FdbkAccN + FdbkTypeN
  PA ~ a11*FdbkValN + d21*DJ
  Na ~ a21*FdbkValN + d11*DJ
  Activation ~ DJ
'
#Fit SEM to data
fitd <- lavaan::sem(DissSEM4, data, std.lv = TRUE, estimator = "WLSMV")
summary(fitd, fit.measures=TRUE, standardized = TRUE, rsquare=TRUE, ci=TRUE)
MI <- modindices(fitd)
write.csv(MI, file = "DissSEM.csv")
factor.scores <- predict(fitb)
factor.scores <- as.data.frame(factor.scores)
factor.scores <- as.data.frame(factor.scores$POFA)
names(factor.scores) <- c("POFA")

#compare models
anova(fitc,fitd)

#To visualize the model, load 'semPlot'.
semPaths(fitc,  layout = "spring", edge.label.cex = 0.5, curvePivot = TRUE, intercepts = FALSE, residuals = FALSE, thresholds = FALSE, structural = FALSE, gui = TRUE, intStyle = "multi")

# Examine residuals
resid(fitd, type = 'raw')
resid(fitd, type = 'cor')

# Extract unique correlation residuals
fitCorResiduals <- resid(fitd, type = 'cor')$cov
fitCorResidualsUnique <- fitCorResiduals[lower.tri(fitCorResiduals, diag = TRUE)]

# View summary of stem-and-leaf plot
summary(fitCorResidualsUnique)
stem(fitCorResidualsUnique)

# Another plot option
plot(fitCorResidualsUnique[order(fitCorResidualsUnique)], pch=16, 
     xlab='', ylab = 'Correlation Residual')

# Flag residual GT .1 or LT -.1 (choose own threshold)
flaggedResiduals <- which(abs(fitCorResiduals) > .1, arr.ind=TRUE)
flaggedValues <- fitCorResiduals[flaggedResiduals]
flaggedRowNames <- rownames(fitCorResiduals)[flaggedResiduals[1:5,1]]
flaggedColNames <- colnames(fitCorResiduals)[flaggedResiduals[1:5,2]]
myFlaggedResiduals <- data.frame(flaggedRowNames, flaggedColNames, flaggedValues[1:5])
# These appear to be method effects (avoid correlating residuals). 

# Print covariance matrix of accepted model to allow for independent reproducibiliity
fitted(fitd)

#Note: this is the code that was used to identify outliers trimmed in a previous chunk.
#Getting generalized Cooks Distance and DFBETAs.
#x <- gCD(data,DissSEM1,progress = TRUE)
#Index plot for gCD.
#plot(x, y = NULL, main = "Generalized Cook Distance",  type = c("p", "h"), ylab = "gCD")
#Print out top 10 cases.
#print(x, ncases = 10, stat = "gCD")

#To visualize/plot the intraction effects, run ANOVAs and plot the results.
##Create scale scores for POFA
my.keys <- make.keys(data,list(scale1 = c(31,32,33,34,35))) #etc 
my.scale <- scoreItems(my.keys,data)
my.scale
AccTy <- cbind(factor.scores,my.scale[["scores"]],data)
fit <- aov(POFA ~ FdbkTypeN:FdbkAccN + FdbkValN + FdbkTypeN, data=AccTy) # There appear to be direct effects linking FIT and FA to POFA.
summary(fit)
#H5: When feedback is nominal, there is a positive and strong relationship between feedback accuracy and POFA. When Feedback is relative, there is not relationship linking feedback acccuracy to POFA. 
#subset data into two smaller groups, compute t-statistic and test. 
#nominal
AccTyN <- AccTy[ which(AccTy$FdbkTypeN=='2'),]
t.test(AccTyN$scale1~AccTyN$FdbkAccN)
cohen.d(AccTyN, "FdbkAccN")
boxplot(AccTyN$scale1~AccTyN$FdbkAccN)
#relative
AcctyR <- AccTy[ which(AccTy$FdbkTypeN=='1'),]
t.test(AcctyR$scale1~AcctyR$FdbkAccN)
cohen.d(AcctyR, "FdbkAccN")
boxplot(AcctyR$scale1~AcctyR$FdbkAccN)

#require(graphics)
AccTy$FdbkTypeN <- as.factor(AccTy$FdbkTypeN)
AccTy$FdbkAccN <- as.factor(AccTy$FdbkAccN)
AccTy$FdbkValN <- as.factor(AccTy$FdbkValN)

#Plots using ggplot2
##Accuracy & Type
dat2 <- describeBy(AccTy$scale1,list(AccTy$FdbkTypeN,AccTy$FdbkAccN), mat=TRUE,digits=2) #POFA
##Calculate summary statistics for POFA by IVs.
names(dat2)[names(dat2) == 'group1'] = 'FeedbackType'
names(dat2)[names(dat2) == 'group2'] = 'FeedbackAccuracy'
levels(dat2$FeedbackType)[levels(dat2$FeedbackType)=='1'] = 'Relative'
levels(dat2$FeedbackType)[levels(dat2$FeedbackType)=='2'] = 'Nominal'
levels(dat2$FeedbackAccuracy)[levels(dat2$FeedbackAccuracy)=='1'] = 'Inaccurate'
levels(dat2$FeedbackAccuracy)[levels(dat2$FeedbackAccuracy)=='2'] = 'Accurate'
dat2$se <- dat2$sd/sqrt(dat2$n)
limits <- aes(ymax = mean + (1.96*se), ymin=mean - (1.96*se))
dodge <- position_dodge(width=1)
apatheme=theme_bw()+
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text=element_text(family='Times'))
plot1 <- ggplot(dat2, aes(x = FeedbackType, y = mean, fill = FeedbackAccuracy))+
  geom_bar(stat='identity', position=dodge)+
  geom_errorbar(limits, position=dodge, width=0.25)+
  apatheme+
  ylab('Perceptions of Feedback Accuracy (POFA)')+
  scale_fill_grey()
plot1
ggsave('accXtype.png', width=6, height=6, unit='in', dpi=300)

# chi-square result
library(MASS)
tbl <- table(data$FdbkValN,data$FdbkAccN)
chisq.test(tbl)
```

```{r Supplemental analysis and plots}
DissSEM4 <- ' #No affective polarity factor
  # latent variable definitions - Bifactor added
    POFA   =~ PercepAcc1 + PercepAcc2 + PercepAcc3 + PercepAcc4Reco + PercepAcc5
    PA =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert
    Na =~ Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable
    DJ =~ DisJust1 + DisJust2  + DisJust3 + DisJust4

#Bifactor
#Activation =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert + Distressed + Upset + #Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable

#Constrain PA and Na covariance to 0
#    PA~~0*Na
#    PA~~0*Activation
#    Na~~0*Activation

#Outcome Model
  Perf1 ~ Goal1Lvl
  Perf2 ~ f11*Goal2Lvl + Perf1
  
#Mediators Model
  Goal2Lvl ~ Goal1Lvl + e3*DJ + a41*FdbkValN + PA + Na
  DJ ~ c21*POFA + FdbkValN
  POFA ~ a31*FdbkValN + b42*INTAccType
  PA ~ a11*FdbkValN + d21*DJ
  Na ~ a21*FdbkValN + d11*DJ
'

#Fit SEM to data
fitd <- lavaan::sem(DissSEM4, data, std.lv = TRUE, estimator = "WLSMV")
summary(fitd, fit.measures=TRUE, standardized = TRUE, rsquare=TRUE, ci=TRUE)
MI <- modindices(fitd)
write.csv(MI, file = "DissSEM.csv")
factor.scores <- predict(fitb)
factor.scores <- as.data.frame(factor.scores)
factor.scores <- as.data.frame(factor.scores$POFA)
names(factor.scores) <- c("POFA")

#compare models
anova(fitc,fitd)

DissSEM5 <- ' #no direct effect from FV to goal setting
  # latent variable definitions - Bifactor added
    POFA   =~ PercepAcc1 + PercepAcc2 + PercepAcc3 + PercepAcc4Reco + PercepAcc5
    PA =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert
    Na =~ Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable
    DJ =~ DisJust1 + DisJust2  + DisJust3 + DisJust4

#Bifactor
Activation =~ Interested + Excited + Strong + Enthusiastic + Proud + Determined + Attentive + Active + Inspired + Alert + Distressed + Upset + Guilty + Scared + Hostile + Ashamed + Nervous + Afraid + Jittery + Irritable

#Constrain PA and Na covariance to 0
    PA~~0*Na
    PA~~0*Activation
    Na~~0*Activation

#Outcome Model
  Perf1 ~ Goal1Lvl
  Perf2 ~ f11*Goal2Lvl + Perf1
  
#Mediators Model
  Goal2Lvl ~ Goal1Lvl + e3*DJ + PA + Na
  DJ ~ c21*POFA + FdbkValN
  POFA ~ a31*FdbkValN + b42*INTAccType
  PA ~ a11*FdbkValN + d21*DJ
  Na ~ a21*FdbkValN + d11*DJ
'
#Fit SEM to data
fite <- lavaan::sem(DissSEM5, data, std.lv = TRUE, estimator = "WLSMV")
summary(fite, fit.measures=TRUE, standardized = TRUE, rsquare=TRUE, ci=TRUE)
MI <- modindices(fite)
write.csv(MI, file = "DissSEM.csv")
factor.scores <- predict(fitb)
factor.scores <- as.data.frame(factor.scores)
factor.scores <- as.data.frame(factor.scores$POFA)
names(factor.scores) <- c("POFA")

#compare models
anova(fitc,fitb)

#TypeAccuracy Interaction on goal setting
dat2 <- describeBy(AccTy$Goal2Lvl,list(AccTy$FdbkTypeN,AccTy$FdbkAccN), mat=TRUE,digits=2) #POFA
##Calculate summary statistics for POFA by IVs.
names(dat2)[names(dat2) == 'group1'] = 'FeedbackType'
names(dat2)[names(dat2) == 'group2'] = 'FeedbackAccuracy'
levels(dat2$FeedbackType)[levels(dat2$FeedbackType)=='1'] = 'Relative'
levels(dat2$FeedbackType)[levels(dat2$FeedbackType)=='2'] = 'Nominal'
levels(dat2$FeedbackAccuracy)[levels(dat2$FeedbackAccuracy)=='1'] = 'Inaccurate'
levels(dat2$FeedbackAccuracy)[levels(dat2$FeedbackAccuracy)=='2'] = 'Accurate'
dat2$se <- dat2$sd/sqrt(dat2$n)
limits <- aes(ymax = mean + (1.96*se), ymin=mean - (1.96*se))
dodge <- position_dodge(width=1)
apatheme=theme_bw()+
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text=element_text(family='Times'))
plot2 <- ggplot(dat2, aes(x = FeedbackType, y = mean, fill = FeedbackAccuracy))+
  geom_bar(stat='identity', position=dodge)+
  geom_errorbar(limits, position=dodge, width=0.25)+
  apatheme+
  ylab('Goal Setting at Time2')+
  scale_fill_grey()
plot2

#TypeAccuracy interarction on performance
dat2 <- describeBy(AccTy$Perf2,list(AccTy$FdbkTypeN,AccTy$FdbkAccN), mat=TRUE,digits=2) #POFA
##Calculate summary statistics for POFA by IVs.
names(dat2)[names(dat2) == 'group1'] = 'FeedbackType'
names(dat2)[names(dat2) == 'group2'] = 'FeedbackAccuracy'
levels(dat2$FeedbackType)[levels(dat2$FeedbackType)=='1'] = 'Relative'
levels(dat2$FeedbackType)[levels(dat2$FeedbackType)=='2'] = 'Nominal'
levels(dat2$FeedbackAccuracy)[levels(dat2$FeedbackAccuracy)=='1'] = 'Inaccurate'
levels(dat2$FeedbackAccuracy)[levels(dat2$FeedbackAccuracy)=='2'] = 'Accurate'
dat2$se <- dat2$sd/sqrt(dat2$n)
limits <- aes(ymax = mean + (1.96*se), ymin=mean - (1.96*se))
dodge <- position_dodge(width=1)
apatheme=theme_bw()+
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text=element_text(family='Times'))
plot3 <- ggplot(dat2, aes(x = FeedbackType, y = mean, fill = FeedbackAccuracy))+
  geom_bar(stat='identity', position=dodge)+
  geom_errorbar(limits, position=dodge, width=0.25)+
  apatheme+
  ylab('Performance at Time 2')+
  scale_fill_grey()
plot3

#TypeValence Interaction on goal setting
dat2 <- describeBy(AccTy$Goal2Lvl,list(AccTy$FdbkTypeN,AccTy$FdbkValN), mat=TRUE,digits=2) #POFA
##Calculate summary statistics for POFA by IVs.
names(dat2)[names(dat2) == 'group1'] = 'FeedbackType'
names(dat2)[names(dat2) == 'group2'] = 'FeedbackValence'
levels(dat2$FeedbackType)[levels(dat2$FeedbackType)=='1'] = 'Relative'
levels(dat2$FeedbackType)[levels(dat2$FeedbackType)=='2'] = 'Nominal'
levels(dat2$FeedbackValence)[levels(dat2$FeedbackValence)=='1'] = 'Negative'
levels(dat2$FeedbackValence)[levels(dat2$FeedbackValence)=='2'] = 'Positive'
dat2$se <- dat2$sd/sqrt(dat2$n)
limits <- aes(ymax = mean + (1.96*se), ymin=mean - (1.96*se))
dodge <- position_dodge(width=1)
apatheme=theme_bw()+
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text=element_text(family='Times'))
plot4 <- ggplot(dat2, aes(x = FeedbackType, y = mean, fill = FeedbackValence))+
  geom_bar(stat='identity', position=dodge)+
  geom_errorbar(limits, position=dodge, width=0.25)+
  apatheme+
  ylab('Goal Setting at Time2')+
  scale_fill_grey()
plot4

#TypeAccuracy interarction on performance
dat2 <- describeBy(AccTy$Perf2,list(AccTy$FdbkTypeN,AccTy$FdbkAccN), mat=TRUE,digits=2) #POFA
##Calculate summary statistics for POFA by IVs.
names(dat2)[names(dat2) == 'group1'] = 'FeedbackType'
names(dat2)[names(dat2) == 'group2'] = 'FeedbackValence'
levels(dat2$FeedbackType)[levels(dat2$FeedbackType)=='1'] = 'Relative'
levels(dat2$FeedbackType)[levels(dat2$FeedbackType)=='2'] = 'Nominal'
levels(dat2$FeedbackValence)[levels(dat2$FeedbackValence)=='1'] = 'Negative'
levels(dat2$FeedbackValence)[levels(dat2$FeedbackValence)=='2'] = 'Positive'
dat2$se <- dat2$sd/sqrt(dat2$n)
limits <- aes(ymax = mean + (1.96*se), ymin=mean - (1.96*se))
dodge <- position_dodge(width=1)
apatheme=theme_bw()+
  theme(panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.border=element_blank(),
        axis.line=element_line(),
        text=element_text(family='Times'))
plot5 <- ggplot(dat2, aes(x = FeedbackType, y = mean, fill = FeedbackValence))+
  geom_bar(stat='identity', position=dodge)+
  geom_errorbar(limits, position=dodge, width=0.25)+
  apatheme+
  ylab('Performance at Time 2')+
  scale_fill_grey()
plot5
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
